version: "3.8"
services:    
  backend:
    container_name: backend
    build:
      context: ./backend
      args:        
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        SERPAPI_API_KEY: ${SERPAPI_API_KEY}
        BROKER_URL: ${BROKER_URL}
    volumes:
      - ./backend:/app
    command: sh -c "pip3 install --upgrade pip && pip3 install -r requirements.txt && export PYTHONPATH=/app && uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
    environment:
      - PYTHONPATH=/app
    ports:
      - "8003:8003"
    depends_on:
      - tritonserver

  app:
    container_name: react-app
    build:
      context: ./frontend
    ports:
      - 8080:80
    depends_on:
      - gradio-app

  tritonserver:
    build:
      context: ./models
      dockerfile: Dockerfile
    command: /bin/bash -c "tritonserver --model-store ./model_repository"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/work
    working_dir: /work
    #shm_size: 8G
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
    stdin_open: true
    tty: true

  gradio-app:
    build:
      context: ./gradio
    ports:
      - "7860:7860"
    environment:
      - NO_PROXY=localhost
    # depends_on:
    #   - backend
