version: "3.8"
services:    
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     args:        
  #       OPENAI_API_KEY: ${OPENAI_API_KEY}
  #       SERPAPI_API_KEY: ${SERPAPI_API_KEY}
  #       BROKER_URL: ${BROKER_URL}
  #   volumes:
  #     - ./backend:/app
  #   command: sh -c "pip3 install --upgrade pip && pip3 install -r requirements.txt && export PYTHONPATH=/app && uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
  #   environment:
  #     - PYTHONPATH=/app
  #   ports:
  #     - "8003:8003"
  #   depends_on:
  #     - tritonserver

  # app:
  #   container_name: react-app
  #   build:
  #     context: ./frontend
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - tritonserver

  vllmserver:
    build:
      context: ./models
      dockerfile: Dockerfile
    #command: /bin/bash -c "tritonserver --model-store ./model_repository"
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8000:8000"
    volumes:
      - ./models:/work
    working_dir: /work
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
    stdin_open: true
    tty: true

